name: 'Install Vulkan SDK'
description: 'Installs the Vulkan SDK and sets the VULKAN_SDK environment variable'
inputs:
  vulkan-version:
    description: 'specify a Vulkan SDK release version, e.g. 1.2.162.1'
    default: 'latest'
    required: false
runs:
  using: "composite"
  steps: 
    - name: Download and extract Vulkan SDK
      shell: bash
      run: |
        VK_VERSION=${{ inputs.vulkan-version }}
        mkdir vulkan_sdk
        if [ `uname -m` != 'x86_64' ]; then echo 'Error: Not supported platform.' && exit 1; fi
        case `uname -s` in
          Linux)
             if [ "$VK_VERSION" == "latest" ]; then
               VULKAN_SDK_FILE=vulkan-sdk.tar.gz
               VULKAN_SDK_URL=https://sdk.lunarg.com/sdk/download/latest/linux/$VULKAN_SDK_FILE?u=
             else
               VULKAN_SDK_FILE=vulkansdk-linux-x86_64-$VK_VERSION.tar.gz
               VULKAN_SDK_URL=https://sdk.lunarg.com/sdk/download/$VK_VERSION/linux/$VULKAN_SDK_FILE
             fi
             wget -q -O $VULKAN_SDK_FILE $VULKAN_SDK_URL
             tar -C vulkan_sdk -zxf $VULKAN_SDK_FILE
             VULKAN_SDK=$(ls vulkan_sdk/*/x86_64 -d)
             VULKAN_SDK_ROOT=$PWD/vulkan_sdk/`echo $(cd vulkan_sdk && ls)`
             echo "VULKAN_SDK=$VULKAN_SDK" | tee -a $GITHUB_ENV
             echo "VULKAN_SDK_ROOT=$VULKAN_SDK_ROOT" | tee -a $GITHUB_ENV
             # rm $VULKAN_SDK_FILE
            ;;
          Darwin)
            ;;
          *) # Windows
             if [ "$VK_VERSION" == "latest" ]; then
               VULKAN_SDK_FILE=vulkan-sdk.exe
               VULKAN_SDK_URL=https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-sdk.exe?u=
             else
               VULKAN_SDK_FILE=VulkanSDK-$VK_VERSION-Installer.exe
               VULKAN_SDK_URL=https://sdk.lunarg.com/sdk/download/$VK_VERSION/windows/VulkanSDK-$VK_VERSION-Installer.exe?Human=true
             fi
             curl -s $VULKAN_SDK_URL -o $VULKAN_SDK_FILE
             7z x -aoa ./$VULKAN_SDK_FILE -ovulkan_sdk > nul
             echo "VULKAN_SDK_ROOT=$PWD/vulkan_sdk" | tee -a $GITHUB_ENV
             echo "VULKAN_SDK=$PWD/vulkan_sdk" | tee -a $GITHUB_ENV
             # rm $VULKAN_SDK_FILE
            ;;
        esac
        VULKAN_SDK_VERSION=$(cat `find vulkan_sdk -name VkLayer_api_dump.json` | grep api_version | sed -e 's/^.*: "//;s/",//;')
        echo "VULKAN_SDK_VERSION=$VULKAN_SDK_VERSION" | tee -a $GITHUB_ENV
