name: Setup
on: [push]

jobs:
  setup-ubuntu-without-version:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - name: Test Vulkan SDK
        run: |
          echo "Vulkan SDK downloaded from '$VULKAN_SDK_URL'"
          echo "Vulkan SDK detected app_version '$VULKAN_SDK_VERSION'"
          test -n "$VULKAN_SDK_VERSION"

  setup-ubuntu-with-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          vulkan-version: 1.2.162.0
      - name: Test Vulkan SDK
        run: |
          echo "Vulkan SDK downloaded from '$VULKAN_SDK_URL'"
          echo "Vulkan SDK detected app_version '$VULKAN_SDK_VERSION'"
          test -n "$VULKAN_SDK_VERSION"

  setup-windows-with-version:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          vulkan-version: 1.2.162.0
      - name: Test Vulkan SDK
        run: |
          echo "Vulkan SDK downloaded from '$VULKAN_SDK_URL'"
          echo "Vulkan SDK detected app_version '$VULKAN_SDK_VERSION'"
          test -n "$VULKAN_SDK_VERSION"

  setup-windows-without-version:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - name: Test Vulkan SDK
        run: |
          echo "Vulkan SDK downloaded from '$VULKAN_SDK_URL'"
          echo "Vulkan SDK detected app_version '$VULKAN_SDK_VERSION'"
          test -n "$VULKAN_SDK_VERSION"
