name: Setup
on: [push]

jobs:
  setup-ubuntu-without-version:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - run: |
          echo "using Vulkan SDK version '$VK_VERSION'"
          test -n "$VK_VERSION"

  setup-ubuntu-with-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          vulkan-version: 1.2.162.0
      - run: |
          echo "using Vulkan SDK version '$VK_VERSION'"
          test -n "$VK_VERSION"

  setup-windows-with-version:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          vulkan-version: 1.2.162.0
      - run: |
          echo "using Vulkan SDK version '$VK_VERSION'"
          test -n "$VK_VERSION"

  setup-windows-without-version:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - run: |
          echo "using Vulkan SDK version '$VK_VERSION'"
          test -n "$VK_VERSION"
