name: Setup
on: [push]

jobs:
  setup-both-with-versions:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          vulkan-version-linux: 1.2.154.0
          vulkan-version-windows: latest
      - name: Test Vulkan SDK Install
        shell: bash
        run: |
          echo "Vulkan SDK Version=='$VULKAN_SDK_VERSION'"
          echo "VULKAN_SDK=='$VULKAN_SDK'"
          test -n "$VULKAN_SDK_VERSION"
          cmake -B tests/build -S tests -DCMAKE_BUILD_TYPE=Release -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=.
          cmake --build tests/build --config release
          PATH=$PATH:$VULKAN_SDK/bin ./tests/build/test_vulkan

  setup-ubuntu-without-version:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:16.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - name: Test Vulkan SDK Install
        run: |
          echo "Vulkan SDK Version=='$VULKAN_SDK_VERSION'"
          echo "VULKAN_SDK=='$VULKAN_SDK'"
          test -n "$VULKAN_SDK_VERSION"
          cmake -B tests/build -S tests -DCMAKE_BUILD_TYPE=Release -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=.
          cmake --build tests/build --config release
          PATH=$PATH:$VULKAN_SDK/bin ./tests/build/test_vulkan

  setup-ubuntu-with-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          vulkan-version: 1.2.162.0
      - name: Test Vulkan SDK Install
        run: |
          echo "Vulkan SDK Version=='$VULKAN_SDK_VERSION'"
          echo "VULKAN_SDK=='$VULKAN_SDK'"
          test -n "$VULKAN_SDK_VERSION"
          cmake -B tests/build -S tests -DCMAKE_BUILD_TYPE=Release -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=.
          cmake --build tests/build --config release
          PATH=$PATH:$VULKAN_SDK/bin ./tests/build/test_vulkan

  setup-ubuntu-with-sdk-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          vulkan-version: sdk-1.1.101
      - name: Test Vulkan SDK Install
        run: |
          echo "Vulkan SDK Version=='$VULKAN_SDK_VERSION'"
          echo "VULKAN_SDK=='$VULKAN_SDK'"
          test -n "$VULKAN_SDK_VERSION"
          cmake -B tests/build -S tests -DCMAKE_BUILD_TYPE=Release -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=.
          cmake --build tests/build --config release
          PATH=$PATH:$VULKAN_SDK/bin ./tests/build/test_vulkan

  setup-windows-without-version-cmd:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - name: Test Vulkan SDK Install
        shell: cmd
        run: |
          echo "Vulkan SDK Version=='%VULKAN_SDK_VERSION%'"
          echo "VULKAN_SDK=='%VULKAN_SDK%'"
          if "%VULKAN_SDK_VERSION%"=="" exit 1
          cmake -B tests/build -S tests -DCMAKE_BUILD_TYPE=Release -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=. || exit /b 1
          cmake --build tests/build --config release || exit /b 1
          set PATH=%PATH%;%VULKAN_SDK%/bin
          .\tests\build\test_vulkan || exit /b 1


  setup-windows-with-version-powershell:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          vulkan-version: 1.2.154.0
      - name: Test Vulkan SDK Install
        shell: powershell
        run: |
          echo "Vulkan SDK Version=='$env:VULKAN_SDK_VERSION'"
          if (!$env:VULKAN_SDK_VERSION) { throw "vulkan sdk install error" }
          cmake -B tests/build -S tests -DCMAKE_BUILD_TYPE=Release -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=.
          cmake --build tests/build --config release
          $ENV:PATH="$ENV:PATH;$ENV:VULKAN_SDK/bin"
          ./tests/build/test_vulkan
